services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./mysql/sqls/manses.sql:/docker-entrypoint-initdb.d/manses.sql
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
