spring:
  application:
    name: mansereok-server

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

# OpenAI API
openai:
  api:
    key: ${OPENAI_API_KEY}
    base-url: https://api.openai.com

# Gemini API
gemini:
  api:
    key: ${GEMINI_API_KEY}
    base-url: https://generativelanguage.googleapis.com/v1beta/models

# 만세력 불러올 API
posteller:
  api:
    base-url: https://api.forceteller.com

# swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# JWT
app:
  jwt:
    secret: "mySecretKey12345678901234567890123456789012345678901234567890"
    access-token-expiration: 1800000   # 30분 (밀리초)
    refresh-token-expiration: 2592000000 # 30일 (밀리초)
    issuer: "com.example.app" # 추후에 서비스 이름 정해지면 수정 ..

server:
  port: 8080
